[General]
fail_count=1
immwvtcotualalt06v75ig%40xmpp.zoom.us.asyn.enc.db=1
immwvtcotualalt06v75ig%40xmpp.zoom.us.enc.db=1
immwvtcotualalt06v75ig%40xmpp.zoom.us.idx.enc.db=1
immwvtcotualalt06v75ig%40xmpp.zoom.us.sync.enc.db=1
initialize_flag=1
random_key="rxJVu/xaE5esHMzOo10rT4fjaUKYV9Ei1PNI+PWboYg="
