[shell]
     program = "/bin/zsh"

[font]
     normal = { family = '0xProto Nerd Font Mono', style = 'Regular' }

[window]
     opacity = 0.85
     dynamic_padding = false
     padding = {x = 10}

[colors.normal]
     black = "#151720"
     red = "#e610de"
     green = "#8b39ad"
     yellow = "#a82ee6"
     blue = "#5f34e0"
     magenta = "#623b8a"
     cyan = "#7910c4"
     white = "#c39ee8"

[colors.bright]
     black = "#343a52"
     red = "#cf3e95"
     green = "#bb66de"
     yellow = "#f54cd1"
     blue = "#714be3"
     magenta = "#9056cc"
     cyan = "#a42ff7"
     white = "#c39ee8"
