[terminal.shell]
     program = "/bin/zsh"

[font]
     size = 13
     normal = { family = '0xProto Nerd Font Mono', style = 'Regular' }

[window]
     opacity = 0.75
     dynamic_padding = false
     padding = {x = 10}

[colors.bright]
     black = "#151720"
     blue = "#7da6ff"
     cyan = "#0db9d7"
     green = "#b9f27c"
     magenta = "#bb9af7"
     red = "#ff7a93"
     white = "#acb0d0"
     yellow = "#ff9e64"

[colors.normal]
     black = "#151720"
     blue = "#7aa2f7"
     cyan = "#449dab"
     green = "#9ece6a"
     magenta = "#ad8ee6"
     red = "#f7768e"
     white = "#787c99"
     yellow = "#e0af68"

